[project]
name = "mental-models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "wikipedia-api>=0.8.1",
]
